export const team = [
    {
        Name: 'Engineering',
        Description:
            'There are three subteams of Engineering: Web Development, Algorithms, and Data Analysis. The <strong>Web Dev</strong> subteam builds the front-end and back-end of the Perfect Match website. The <strong>Algorithms</strong> subteam improves the matching algorithm that matches students based on their preferences. The <strong>Data Analysis</strong> subteam analyzes and visualizes the data collected from the Perfect Match survey.',
        Members: [
            {
                Name: 'Daniel Chuang',
                ClassYear: 2026,
                Major: 'CS & Math',
                Img: '/members/daniel.png',
                Linkedin: 'https://www.linkedin.com/in/daniel-chuang-7a1bb920b/',
                Title1: 'Engineering Team Lead',
                Title2: 'Data Analysis Subteam Head',
            },
            {
                Name: 'Cindy Li',
                ClassYear: 2027,
                Major: 'CS',
                Img: '/members/cindy.jpg',
                Linkedin: ' https://www.linkedin.com/in/cindy-li-569a30187/',
                Title1: 'Engineering Team Lead',
                Title2: 'Algorithms & Web Dev Subteam Member',
            },
            {
                Name: 'Joyce Shen',
                ClassYear: 2027,
                Major: 'CS & ECE',
                Img: '/members/joyce.png',
                Linkedin: 'https://www.linkedin.com/in/jshen127/',
                Title1: 'Algorithms Subteam Head',
            },
            {
                Name: 'Huajie Zhong',
                ClassYear: 2027,
                Major: 'CS',
                Img: '/members/huajie.png',
                Linkedin: 'https://www.linkedin.com/in/huajiezhong/',
                Title1: 'Web Dev Subteam Head',
            },
            {
                Name: 'Pratyush Sudhakar',
                ClassYear: 2025,
                Major: 'CS & Math',
                Img: '/members/pratyush.jpg',
                Team: 'Engineering',
                Linkedin: 'https://www.linkedin.com/in/pratyushsudhakar',
                Title1: 'Algorithms & Web Dev Subteam Member',
            },
            {
                Name: 'Ashlie Zhang',
                ClassYear: 2027,
                Major: 'CS',
                Img: '/members/ashlie.png',
                Linkedin: 'https://www.linkedin.com/in/ashlie-zhang-8982b7296/',
                Title1: 'Web Dev Subteam Member',
            },
            {
                Name: 'Evan Wang',
                ClassYear: 2028,
                Major: 'CS',
                Img: '/members/evan.jpg',
                Linkedin: 'https://www.linkedin.com/in/evan-wang-938b73274/',
                Title1: 'Web Dev Subteam Member',
            },
            {
                Name: 'Eunice Son',
                ClassYear: 2028,
                Major: 'ORIE',
                Img: '/members/eunice.jpg',
                Linkedin: 'https://www.linkedin.com/in/eunice-son-015148248',
                Title1: 'Data Analytics Subteam Member',
            },
            {
                Name: 'Alex Saccone',
                ClassYear: 2028,
                Major: 'CS & Math',
                Img: '/members/alex.png',
                Linkedin: 'https://www.linkedin.com/in/alex-saccone-3b9679234/',
                Title1: 'Data Analytics Subteam Member',
            },
            {
                Name: 'Ashir Rao',
                ClassYear: 2028,
                Major: 'CS',
                Img: '/members/ashir.png',
                Linkedin:
                    'https://www.linkedin.com/in/ashir-rao-82a66a225/',
                Title1: 'Web Dev Subteam Member',
            },
            {
                Name: 'Aileen Huang',
                ClassYear: 2026,
                Major: 'CS',
                Img: '/members/aileen.jpg',
                Linkedin:
                    'https://www.linkedin.com/in/aileen-huang-802a04260/',
                Title1: 'Data Analytics Subteam Member',
            },

        ],
    },
    {
        Name: 'Business',
        Description:
            'There are two subteams of Business: Design and Business. The <strong>Design</strong> subteam conducts research to learn more about Perfect Match’s user in order to iterate on the product. The <strong>Business</strong> subteam is responsible for marketing Perfect Match and reaching out to potential sponsors/partners.',
        Members: [
            {
                Name: 'Kelly Hong',
                ClassYear: 2027,
                Major: 'Fine Arts',
                Img: '/members/kelly.png',
                Linkedin: 'https://www.linkedin.com/in/kelly-hong-64666b294/ ',
                Title1: 'Business Team Lead',
                Title2: 'Designer',
            },
            {
                Name: 'Sam Smith',
                ClassYear: 2026,
                Major: 'Information Science',
                Img: '/members/sam.jpeg',
                Linkedin:
                    'https://www.linkedin.com/in/samantha-smith-057302251/?profileId=ACoAAD4owcMBUJd9F2pVXmgf5ClwGk_KIu2gmrM/',
                Title1: 'Business Team Lead',
                Title2: 'Designer',
            },
            {
                Name: 'Elif Yilmaz',
                ClassYear: 2027,
                Major: 'Econ & Gov',
                Img: '/members/elif.png',
                Linkedin: ' https://www.linkedin.com/in/elif-naz-yilmaz/',
                Title1: 'Business Team Lead',
            },
            {
                Name: 'Connie Zhang',
                ClassYear: 2027,
                Major: 'Information Science',
                Img: '/members/connie.png',
                Linkedin: 'https://www.linkedin.com/in/connie-zhang-profile',
                Title1: 'Designer',
            },
            {
                Name: 'Seojin Park',
                ClassYear: 2028,
                Major: 'Fine/Studio Arts',
                Img: '/members/seojin.png',
                Linkedin: 'https://www.linkedin.com/in/seojinparkart/',
                Title1: 'Designer',
            },
            {
                Name: 'Carl Hu',
                ClassYear: 2028,
                Major: 'CS',
                Img: '/members/carl.jpg',
                Linkedin: 'https://www.linkedin.com/in/carl-hu/',
                Title1: 'Business Team Member',
            },
            {
                Name: 'Diya Lavu',
                ClassYear: 2026,
                Major: 'Econ',
                Img: '/members/diya.jpg',
                Linkedin:
                    'https://www.linkedin.com/in/diyalavu/',
                Title1: 'Business Team Member',
            },
            // {
            //     Name: 'Lucy Yang',
            //     ClassYear: 2026,
            //     Major: 'Psychology and Information Science',
            //     Img: '/members/lucy.jpeg',
            //     Linkedin:
            //         'https://www.linkedin.com/in/lucy-yang-ma21/',
            //     Title1: 'Designer',
            // }
        ],
    },
];
